server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://hopper.proxy.rlwy.net:29923/railway?serverTimezone=Asia/Taipei&useSSL=true&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:NAJhTGxCAOIfAsebVxGZPHvPjSJVhbSQ}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Taipei
  threads:
    virtual:
      enabled: true
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  backend:
    url: ${BACKEND_URL:http://localhost:8080}
  jwt:
    secret: ${JWT_SECRET:W8yKx72qzNfL4cRjTgHv9BmQYeUaPdVoXcLtRsMjEnGbKhZwAvCuTxNrJiQwLmEz}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

line:
  client-id: ${LINE_CLIENT_ID}
  client-secret: ${LINE_CLIENT_SECRET}

aes:
  key: ${AES_KEY:d92oUh3gPZvVXIZfEgOVIskZp5Qer9hUHw+JBmCUZM8=}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.volleyball.finder.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    cache-enabled: false
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

resilience4j:
  ratelimiter:
    instances:
      globalLimiter:
        limit-for-period: 120         # 每個週期允許的請求數
        limit-refresh-period: 1m      # 限流周期
        timeout-duration: 0           # 若已達限制，等待多久（0 = 不等待直接失敗）